### ISSUE TITLE
Potential dependency issue when compiling QuickStep

### ISSUE THREAD

**Issue by remysucre** [Hacker0912/RecStep#3]
It doesn't look like I can open issues on the QuickStep repo, so I'm opening one here. The problem is simple - I ran into dependency errors when compiling QuickStep with `make -j12` (I think it was missing grpc files), but was able to resolve with `make` (single-threaded). I believe this suggests a dependency bug in the build script. Sorry that I'm not attaching more detailed errors - the successful build took a very long time and I don't want to repeat that. But lmk if you can't replicate the bug, and I can perhaps leave it running overnight.

**Comment by Hacker0912** [comment]
Hi Remy,

Send me an email (zhiwei@cs.wisc.edu) and we may schedule a video meeting to help you resolve that if you would like to.
